#!/bin/bash
echo "===== PINEAL-HERETIC v2.0 - TERMINAL KANITLI OTOMPSI ====="
echo ""
echo ">> 1. GLOBAL STATE KONTROLU (api.py)"
echo "grep -n 'global\|executor =\|vault =' backend/api.py"
grep -n "global\|executor =\|vault =\|contextvar\|ExecutorContext\|client_id" backend/api.py || echo "DOSYA BULUNAMADI"
echo ""
echo ">> 2. HAFIZA KÖPRÜSÜ KONTROLU (canonical_memory -> task_executor)"
echo "grep -rn 'canonical_memory\|learnings.json\|MemoryInjector' agent_core/ --include='*.py'"
grep -rn "canonical_memory\|learnings.json\|MemoryInjector" agent_core/ --include="*.py"
echo ""
echo "--- task_executor.py icinde memory okuma var mi?"
grep -n "memory\|learnings" agent_core/task_executor.py
echo ""
echo ">> 3. JSON CELIKLESMESI KONTROLU"
echo "grep -rn 'Pydantic\|BaseModel\|extract_json\|repair' agent_core/agents/ --include='*.py'"
grep -rn "Pydantic\|BaseModel\|extract_json\|repair\|json.*decode" agent_core/ --include="*.py" | head -n 50
echo ""
echo ">> 4. SCRAPER ANTI-KIRILGANLIK KONTROLU"
echo "grep -n 'data-testid\|page.on\|route\|GraphQL\|UserByScreenName\|UserTweets\|media_url' scraper.py"
grep -n "data-testid\|page.on\|route\|GraphQL\|UserByScreenName\|UserTweets\|media_url\|intercept" scraper.py
echo ""
echo ">> 5. ROUTER / UNCERTAINTY AKTIF MI?"
echo "grep -rn 'cognitive_router\|uncertainty_engine\|confidence.*0.6\|halt' agent_core/ --include='*.py'"
grep -rn "cognitive_router\|uncertainty_engine\|confidence\|halt\|InsufficientEvidence" agent_core/ --include="*.py"
echo ""
echo ">> 6. DOSYA YAPISI"
ls -R agent_core/services/
echo ""
echo ">> 7. SYNTAX TEST"
python -m py_compile $(find . -name "*.py") && echo "SYNTAX OK" || echo "SYNTAX HATALI"
echo ""
echo ">> 8. CANLI SUNUCU LOGU"
echo "ps aux | grep uvicorn / python"
ps aux | grep -E "uvicorn|api.py" | grep -v grep || echo "Sunucu ayakta degil"
echo ""
echo "===== KANIT SONU ====="
